# Generated by Django 5.2.8 on 2025-11-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="General information about the course"),
                ),
                (
                    "main_info",
                    models.TextField(help_text="Main information about the course"),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, help_text="Additional information for AI context"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("claude", "Claude"), ("gpt", "GPT")],
                        default="gpt",
                        help_text="AI model to use",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional information for AI context",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Chats",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        default="user",
                        help_text="Message sender role",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("voice", "Voice Message"),
                            ("video", "Video"),
                        ],
                        default="text",
                        help_text="Type of content",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content or file path/URL"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Message order in the conversation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["chat", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(help_text="Description of the topic")),
                (
                    "info",
                    models.TextField(
                        help_text="Information about what this topic covers"
                    ),
                ),
                (
                    "learned_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Information that has been learned so far",
                    ),
                ),
                (
                    "expected_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Expected knowledge to compare against for progress calculation",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional topic. If null, chat represents the whole course.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="api.topic",
            ),
        ),
    ]
