# Generated by Django 5.2.8 on 2025-11-30 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='main_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='model',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='order',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='expected_info',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='info',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='learned_info',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('has_news_context', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
